[package]
name = "actix"
version = "0.1.0"
authors = ["Leo Liu <wei.liu@zuora.com>"]

[profile.release]
opt-level = 3

[dependencies]
bytes = "0.4"
futures = "0.1"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"

actix = "*"
actix-web = "*"
